In [2]:
import numpy as np

In [3]:
# 1D array
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)
# 2D array
arr2 = np.array([[1, 2], [3, 4]])
print("2D Array:\n", arr2)

# 3D array
arr3 = np.array([[[1, 2], [3, 4]]])
print("3D Array:\n", arr3)

1D Array: [1 2 3 4]
2D Array:
 [[1 2]
 [3 4]]
3D Array:
 [[[1 2]
  [3 4]]]


In [4]:
arr = np.array([10, 20, 30, 40])

print(arr[0])      # first element
print(arr[1:3])    # slicing

10
[20 30]


In [5]:
arr = np.array([1,2,3,4,5,6])

reshaped = arr.reshape(2,3)

print(reshaped)

[[1 2 3]
 [4 5 6]]


In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a + b)
print("Multiplication:", a * b)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [7]:
arr = np.array([1,2,3])

print(arr + 5)

[6 7 8]


In [8]:
arr = np.array([10,20,30,40])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std Dev:", np.std(arr))
print("Percentile:", np.percentile(arr, 50))

Mean: 25.0
Median: 25.0
Std Dev: 11.180339887498949
Percentile: 25.0


In [9]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print("Dot Product:", np.dot(a,b))
print("Matrix Multiplication:", np.matmul(a,b))

Dot Product: [[19 22]
 [43 50]]
Matrix Multiplication: [[19 22]
 [43 50]]


In [10]:
# random numbers
rand = np.random.rand(3)
print(rand)

# random integers
rand_int = np.random.randint(1,10,5)
print(rand_int)

[0.96721498 0.00814648 0.51015569]
[6 4 5 7 7]


In [11]:
temps = np.array([30, 32, 35, 31, 29, 28, 33])

print("Average Temp:", np.mean(temps))
print("Max Temp:", np.max(temps))
print("Min Temp:", np.min(temps))

Average Temp: 31.142857142857142
Max Temp: 35
Min Temp: 28


In [12]:
import time

# Python list
start = time.time()
lst = [i for i in range(1000000)]
lst = [i+5 for i in lst]
print("List Time:", time.time() - start)

# NumPy
start = time.time()
arr = np.arange(1000000)
arr = arr + 5
print("NumPy Time:", time.time() - start)

List Time: 0.2585911750793457
NumPy Time: 0.010192632675170898
